apiVersion: v1
kind: ServiceAccount
metadata:
  name: egressip-controller
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: egressip-controller
  namespace: kube-system
rules:
  - apiGroups:
    - ""
    resources:
      - namespaces
      - pods
      - services
      - nodes
      - endpoints
      - configmaps
    verbs:
      - list
      - get
      - watch
  - apiGroups:
    - "staticegressips.nirmata.io"
    resources:
      - staticegressips
    verbs:
      - list
      - get
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: egressip-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: egressip-controller
subjects:
- kind: ServiceAccount
  name: egressip-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-egressip-manager
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: static-egressip-manager
  replicas: 2
  template:
    metadata:
      labels:
        name: static-egressip-manager
    spec:
      serviceAccount: egressip-controller
      serviceAccountName: egressip-controller
      containers:
      - name: static-egressip-manager
        image: nirmata/egressip-manager:latest
        imagePullPolicy: Always
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
